name: Run Tests

on:
  push:
    branches:
      - "master"

jobs:
  spec:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby_version:
          - "3.1"
          - "3.2"
          - "3.3"
          - "3.4"
          - "head"

    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby_version }}
        bundler-cache: true

    - name: Run Tests
      run: bundle exec rake
